import legacy from "@vitejs/plugin-legacy";

export const legacyConfig = legacy({
  targets: [
    'safari >= 12',
    'ios >= 12',
    'chrome >= 49',
    'firefox >= 52',
    'edge >= 18',
    'opera >= 36',
    'android >= 4.4'
  ],
  additionalLegacyPolyfills: [
    'regenerator-runtime/runtime',
    'core-js/features/array/find',
    'core-js/features/array/includes',
    'core-js/features/string/includes',
    'core-js/features/promise',
    'core-js/features/object/assign',
    'core-js/features/symbol',
    'core-js/features/set',
    'core-js/features/map',
    'core-js/features/weak-map',
    'core-js/features/weak-set',
    'core-js/features/url',
    'core-js/features/url-search-params',
    'core-js/features/object/entries',
    'core-js/features/object/values',
    'core-js/features/array/from',
    'core-js/features/array/of',
    'core-js/features/string/pad-start',
    'core-js/features/string/pad-end'
  ],
  modernPolyfills: [
    'es.array.iterator',
    'es.promise',
    'es.object.assign',
    'es.promise.finally',
    'es.symbol',
    'es.array.find',
    'es.array.includes',
    'es.string.includes',
    'es.string.pad-start',
    'es.string.pad-end',
    'es.object.entries',
    'es.object.values',
    'es.array.from',
    'es.array.of',
    'es.map',
    'es.set',
    'es.weak-map',
    'es.weak-set',
    'web.url',
    'web.url-search-params'
  ],
  renderLegacyChunks: true,
  polyfills: [
    'es.array.iterator',
    'es.promise',
    'es.object.assign',
    'es.promise.finally',
    'es.symbol',
    'es.array.find',
    'es.array.includes',
    'es.string.includes',
    'es.string.pad-start',
    'es.string.pad-end',
    'es.object.entries',
    'es.object.values',
    'es.array.from',
    'es.array.of',
    'es.map',
    'es.set',
    'es.weak-map',
    'es.weak-set',
    'web.url',
    'web.url-search-params'
  ]
});